-- CREATE TABLES
CREATE TABLE USERS (
    USERID INTEGER NOT NULL, 
    USERNAME LONG VARCHAR NOT NULL, 
    PASSWORD LONG VARCHAR NOT NULL, 
    EMAIL VARCHAR(255), 
    PRIMARY KEY (USERID)
);

CREATE TABLE PRODUCT (
    PRODUCTID INTEGER NOT NULL, 
    PRODUCTNAME VARCHAR(200) NOT NULL, 
    QAUNTITY INTEGER NOT NULL, 
    PRIMARY KEY (PRODUCTID)
);

-- INSERT PRODUCTS (Must happen after table is created)
INSERT INTO PRODUCT (PRODUCTID, PRODUCTNAME, QAUNTITY) VALUES (1, 'Ryzen 5 5600X', 484);
INSERT INTO PRODUCT (PRODUCTID, PRODUCTNAME, QAUNTITY) VALUES (2, 'Core i5-12400F', 56);
INSERT INTO PRODUCT (PRODUCTID, PRODUCTNAME, QAUNTITY) VALUES (3, 'RX 7600', 16);
INSERT INTO PRODUCT (PRODUCTID, PRODUCTNAME, QAUNTITY) VALUES (4, 'RTX 4060', 72);
INSERT INTO PRODUCT (PRODUCTID, PRODUCTNAME, QAUNTITY) VALUES (5, '16GB DDR4', 47);
INSERT INTO PRODUCT (PRODUCTID, PRODUCTNAME, QAUNTITY) VALUES (6, '32GB DDR4', 70);

CREATE TABLE ADDRESSES (
    ADDRESSKEY INTEGER NOT NULL, 
    FKUSERID INTEGER, 
    COUNTRY LONG VARCHAR NOT NULL, 
    CITY LONG VARCHAR NOT NULL, 
    STREET LONG VARCHAR NOT NULL, 
    PRIMARY KEY (ADDRESSKEY),
    CONSTRAINT FK_USERID FOREIGN KEY (FKUSERID) REFERENCES USERS(USERID)
);

CREATE TABLE TRANSACTIONS (
    ORDERID INTEGER NOT NULL, 
    FK_PRODUCTID INTEGER NOT NULL, 
    FK_USERID INTEGER NOT NULL, 
    PURCHASEDQAUNTITY INTEGER NOT NULL, 
    PRIMARY KEY (ORDERID),
    CONSTRAINT FK_PRODUCTID FOREIGN KEY (FK_PRODUCTID) REFERENCES PRODUCT(PRODUCTID),
    CONSTRAINT USERID_FK FOREIGN KEY (FK_USERID) REFERENCES USERS(USERID)
);

CREATE TABLE SAVEDBUILDS (
    BUILDID INTEGER NOT NULL, 
    EMAIL VARCHAR(100), 
    CPU VARCHAR(100), 
    GPU VARCHAR(100), 
    RAM VARCHAR(100), 
    TOTALPRICE DOUBLE, 
    PRIMARY KEY (BUILDID)
);